version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5679:5679"     # Port interne RabbitMQ AMQP
      - "15679:15679"   # Port UI Web (accès localhost:15679)
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  producer:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: producer
    command: node src/producers/producer.js
    depends_on:
      - rabbitmq
    env_file:
      - ../.env

  consumer:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: consumer
    command: node src/consumers/consumer.js
    ports:
      - "8080:8080"  # WebSocket
    depends_on:
      - rabbitmq
    env_file:
      - ../.env

  worker_add:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: worker_add
    command: node src/workers/add.js
    depends_on:
      - rabbitmq
    env_file:
      - ../.env

  worker_sub:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: worker_sub
    command: node src/workers/sub.js
    depends_on:
      - rabbitmq
    env_file:
      - ../.env

  worker_mul:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: worker_mul
    command: node src/workers/mul.js
    depends_on:
      - rabbitmq
    env_file:
      - ../.env

  worker_div:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: worker_div
    command: node src/workers/div.js
    depends_on:
      - rabbitmq
    env_file:
      - ../.env
